pandoc -f gfm  -t gfm  -o out.md Home.md    \
Items-Within-Library.md                     \
Fundamental-Classes-and-Components.md       \
ComplexNumber.md                            \
EThermalMass.md                             \
InterpretedAssembly.md                      \
InterpretedPort.md                          \
InverterRectifierMap.md                     \
MotorGeneratorMap.md                        \
Electric-Port.md                            \
Electric-Node.md                            \
Modeling-Components.md                      \
AeroCable.md                                \
BasicLoad.md                                \
Breaker.md                                  \
Cable.md                                    \
Capacitor.md                                \
ConstantPowerLoad.md                        \
DC_DC_Converter.md                          \
Generator.md                                \
Inductor.md                                 \
Inverter.md                                 \
Motor.md                                    \
Rectifier.md                                \
Resistor.md                                 \
Source.md                                   \
ThermalDuct.md                              \
ThermalHeatExchanger.md                     \
ThermalLoad.md                              \
ThermalTank.md                              \
Examples.md                                 \
baseline.md                                 \
baseline_1to2Bus.md                         \
baseline_2to1Bus.md                         \
baseline_all_elec.md                        \
baseline_all_elecMDP.md                     \
baseline_turboelectric.md                   \
baseline_turboelectricMDP.md                \
cable_and_duct_thermal_test.md              \
cable_test.md                               \
cable_thermal_test.md                       \
power_propagation.md                        \
run_3phase_example.md                       \
run_RLC_example.md                          \
run_R_dc_example.md                         \
thermal_baseline.md                         \
thermal_test.md                             \
transient_baseline.md
# First, make sure all links have the "#" character that says "hey, look for this reference in the document"
sed -i 's+](+](#+g' out.md
# Then, look for repeated #s in our links. If we have any, whack em.
sed -i 's+](##+](#+g' out.md
# Next, make sure all links look for lowercase references. The autogenerated ones that you get from headers are all lowercase.
sed -i 's/](.*)/\L&/g' out.md
# Finally remove .
sed -i -E 's/(#)(.*\.png)/\2/g' out.md
sed -i -E 's/(#)(.*\.jpg)/\2/g' out.md
pandoc --shift-heading-level-by=-1 --toc --number-sections -f gfm -o out.pdf -B title.tex out.md
